### ISSUE TITLE
[Crash]: Hand Glider (hangglider) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by TenKotowsky** [Fuzss/hangglider#3]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

When I tried to open the game this crash occured. It only happens sometimes, not all the time. I've had it two times.
EDIT: I should probably also mention that I've been switaching some mods on and off, so maybe it's a problem with compatibility?

### Crash Report (Required)

https://gist.github.com/TenKotowsky/d688a9fc77af2ee53cc03e94d627434c

### latest.log (Optional)

https://gist.github.com/TenKotowsky/0360a098749c87c830afa2ac4d542047

**Comment by Fuzss** [comment]
Thanks! Fixed in Puzzles Lib v8.0.2.
